let currency_codes = [
  { name: "Afghan Afghani", code: "AFA", iso_a2: "AF" },
  { name: "Albanian Lek", code: "ALL", iso_a2: "AL" },
  { name: "Algerian Dinar", code: "DZD", iso_a2: "DZ" },
  { name: "Angolan Kwanza", code: "AOA", iso_a2: "AO" },
  { name: "Argentine Peso", code: "ARS", iso_a2: "AR" },
  { name: "Benin", code: "CFA", iso_a2: "BJ" },
  { name: "Central African Rep.", code: "CFA", iso_a2: "CF" },
  { name: "Cameroon", code: "CFA", iso_a2: "CM" },
  { name: "Armenian Dram", code: "AMD", iso_a2: "AM" },
  { name: "Austrian Euro", code: "EUR", iso_a2: "AT" },
  { name: "Australian Dollar", code: "AUD", iso_a2: "AU" },
  { name: "Azerbaijani Manat", code: "AZN", iso_a2: "AZ" },
  { name: "Bahamian Dollar", code: "BSD", iso_a2: "BS" },
  { name: "Bangladeshi Taka", code: "BDT", iso_a2: "BD" },
  { name: "Belarusian Ruble", code: "BYR", iso_a2: "BY" },
  { name: "Belgian Euro", code: "EUR", iso_a2: "BE" },
  { name: "Belize Dollar", code: "BZD", iso_a2: "BZ" },
  { name: "Bhutanese Ngultrum", code: "BTN", iso_a2: "BT" },
  { name: "Senegal", code: "CFA", iso_a2: "SN" },
  { name: "Eq. Guinea", code: "CFA", iso_a2: "GQ" },
  { name: "Mali", code: "CFA", iso_a2: "ML" },
  { name: "Bolivian Boliviano", code: "BOB", iso_a2: "BO" },
  { name: "Bosnia-Herzegovina Convertible Mark", code: "BAM", iso_a2: "BA" },
  { name: "Botswanan Pula", code: "BWP", iso_a2: "BW" },
  { name: "Brazilian Real", code: "BRL", iso_a2: "BR" },
  { name: "British Pound Sterling", code: "GBP", iso_a2: "GB" },
  { name: "Brunei Dollar", code: "BND", iso_a2: "BN" },
  { name: "N. Cyprus", code: "TRY", iso_a2: "-99" },
  { name: "Laotian Kip", code: "LAK", iso_a2: "LA" },
  { name: "Bulgarian Lev", code: "BGN", iso_a2: "BG" },
  { name: "Malagasy Ariary", code: "MGA", iso_a2: "MG" },
  { name: "Burundian Franc", code: "BIF", iso_a2: "BI" },
  { name: "Burkina Faso", code: "CFA", iso_a2: "BF" },
  { name: "Togo", code: "CFA", iso_a2: "TG" },
  { name: "Cambodian Riel", code: "KHR", iso_a2: "KH" },
  { name: "Canadian Dollar", code: "CAD", iso_a2: "CA" },
  { name: "Chilean Peso", code: "CLP", iso_a2: "CL" },
  { name: "Chinese Yuan", code: "CNY", iso_a2: "CN" },
  { name: "Colombian Peso", code: "COP", iso_a2: "CO" },
  { name: "Congolese Franc", code: "CDF", iso_a2: "CG" },
  { name: "Costa Rican Colón", code: "CRC", iso_a2: "CR" },
  { name: "Croatian Euro", code: "EUR", iso_a2: "HR" },
  { name: "Cuban Convertible Peso", code: "CUC", iso_a2: "CU" },
  { name: "Cyprus Euro", code: "EUR", iso_a2: "CY" },
  { name: "Czech Republic Koruna", code: "CZK", iso_a2: "CZ" },
  { name: "Ecuador", code: "USD", iso_a2: "EC" },
  { name: "Danish Krone", code: "DKK", iso_a2: "DK" },
  { name: "Djiboutian Franc", code: "DJF", iso_a2: "DJ" },
  { name: "Dominican Peso", code: "DOP", iso_a2: "DO" },
  { name: "Egyptian Pound", code: "EGP", iso_a2: "EG" },
  { name: "Eritrean Nakfa", code: "ERN", iso_a2: "ER" },
  { name: "Estonian Euro", code: "EUR", iso_a2: "EE" },
  { name: "Ethiopian Birr", code: "ETB", iso_a2: "ET" },
  { name: "Falkland Islands Pound", code: "FKP" },
  { name: "Fijian Dollar", code: "FJD", iso_a2: "FK" },
  { name: "Finland Euro", code: "EUR", iso_a2: "FI" },
  { name: "French Euro", code: "EUR", iso_a2: "FR" },
  { name: "Gambian Dalasi", code: "GMD", iso_a2: "GM" },
  { name: "Georgian Lari", code: "GEL", iso_a2: "GE" },
  { name: "German Euro", code: "EUR", iso_a2: "DE" },
  { name: "Ghanaian Cedi", code: "GHS", iso_a2: "GH" },
  { name: "Greek Euro", code: "EUR", iso_a2: "GR" },
  { name: "Greenland", code: "DKK", iso_a2: "GL" },
  { name: "Gabon", code: "CFA", iso_a2: "GA" },
  { name: "Guatemalan Quetzal", code: "GTQ", iso_a2: "GT" },
  { name: "Guinean Franc", code: "GNF", iso_a2: "GN" },
  { name: "Guyanaese Dollar", code: "GYD", iso_a2: "GY" },
  { name: "Haitian Gourde", code: "HTG", iso_a2: "HT" },
  { name: "Guinea-Bissau", code: "CFA", iso_a2: "GW" },
  { name: "Honduran Lempira", code: "HNL", iso_a2: "HN" },
  { name: "Hungarian Forint", code: "HUF", iso_a2: "HU" },
  { name: "Icelandic Króna", code: "ISK", iso_a2: "IS" },
  { name: "C\u00f4te d'Ivoire", code: "CFA", iso_a2: "CI" },
  { name: "Indian Rupee", code: "INR", iso_a2: "IN" },
  { name: "Dem. Rep. Korea", code: "KPW", iso_a2: "KP" },
  { name: "Indonesian Rupiah", code: "IDR", iso_a2: "ID" },
  { name: "Iranian Rial", code: "IRR", iso_a2: "IR" },
  { name: "Iraqi Dinar", code: "IQD", iso_a2: "IQ" },
  { name: "Irish Euro", code: "EUR", iso_a2: "IE" },
  { name: "Israeli New Sheqel", code: "ILS", iso_a2: "IL" },
  { name: "Italian Euro", code: "EUR", iso_a2: "IT" },
  { name: "Jamaican Dollar", code: "JMD", iso_a2: "JM" },
  { name: "Japanese Yen", code: "JPY", iso_a2: "JP" },
  { name: "Jordanian Dinar", code: "JOD", iso_a2: "JO" },
  { name: "Kazakhstani Tenge", code: "KZT", iso_a2: "KZ" },
  { name: "Kenyan Shilling", code: "KES", iso_a2: "KE" },
  { name: "Kuwaiti Dinar", code: "KWD", iso_a2: "KW" },
  { name: "Kyrgystani Som", code: "KGS", iso_a2: "KG" },
  { name: "Latvian Euro", code: "EUR", iso_a2: "LV" },
  { name: "Puerto Rico", code: "USD", iso_a2: "PR" },
  { name: "Lebanese Pound", code: "LBP", iso_a2: "LB" },
  { name: "Lesotho Loti", code: "LSL", iso_a2: "LS" },
  { name: "Liberian Dollar", code: "LRD", iso_a2: "LR" },
  { name: "Libyan Dinar", code: "LYD", iso_a2: "LY" },
  { name: "Lithuanian Euro", code: "EUR", iso_a2: "LT" },
  { name: "Luxembourg Euro", code: "EUR", iso_a2: "LU" },
  { name: "Macedonian Denar", code: "MKD", iso_a2: "MK" },
  { name: "Malawian Kwacha", code: "MWK", iso_a2: "MW" },
  { name: "Malaysian Ringgit", code: "MYR", iso_a2: "MY" },
  { name: "Mauritanian Ouguiya", code: "MRO", iso_a2: "MR" },
  { name: "Mauritian Rupee", code: "MUR", iso_a2: "MR" },
  { name: "Mexican Peso", code: "MXN", iso_a2: "MX" },
  { name: "Timor-Leste", code: "USD", iso_a2: "TL" },
  { name: "Moldovan Leu", code: "MDL", iso_a2: "MD" },
  { name: "Mongolian Tugrik", code: "MNT", iso_a2: "MN" },
  { name: "Moroccan Dirham", code: "MAD", iso_a2: "MA" },
  { name: "Mozambican Metical", code: "MZM", iso_a2: "MZ" },
  { name: "Myanmar Kyat", code: "MMK", iso_a2: "MM" },
  { name: "Namibian Dollar", code: "NAD", iso_a2: "NA" },
  { name: "Nepalese Rupee", code: "NPR", iso_a2: "NP" },
  { name: "Netherlands", code: "EUR", iso_a2: "NL" },
  { name: "New Taiwan Dollar", code: "TWD", iso_a2: "TW" },
  { name: "New Zealand Dollar", code: "NZD", iso_a2: "NZ" },
  { name: "Nicaraguan Córdoba", code: "NIO", iso_a2: "NI" },
  { name: "Nigerian Naira", code: "NGN", iso_a2: "NG" },
  { name: "Norwegian Krone", code: "NOK", iso_a2: "NO" },
  { name: "Omani Rial", code: "OMR", iso_a2: "OM" },
  { name: "Pakistani Rupee", code: "PKR", iso_a2: "PK" },
  { name: "Panamanian Balboa", code: "PAB", iso_a2: "PA" },
  { name: "Papua New Guinean Kina", code: "PGK", iso_a2: "PG" },
  { name: "Paraguayan Guarani", code: "PYG", iso_a2: "PY" },
  { name: "Peruvian Nuevo Sol", code: "PEN", iso_a2: "PE" },
  { name: "Philippine Peso", code: "PHP", iso_a2: "PH" },
  { name: "Polish Zloty", code: "PLN", iso_a2: "PL" },
  { name: "Portugal Euro", code: "EUR", iso_a2: "PT" },
  { name: "Qatari Rial", code: "QAR", iso_a2: "QA" },
  { name: "Romanian Leu", code: "RON", iso_a2: "RO" },
  { name: "Russian Ruble", code: "RUB", iso_a2: "RU" },
  { name: "Rwandan Franc", code: "RWF", iso_a2: "RW" },
  { name: "Salvadoran Colón", code: "SVC", iso_a2: "SV" },
  { name: "Saudi Riyal", code: "SAR", iso_a2: "SA" },
  { name: "Serbian Dinar", code: "RSD", iso_a2: "RS" },
  { name: "Sierra Leonean Leone", code: "SLL", iso_a2: "SL" },
  { name: "Slovak Euro", code: "EUR", iso_a2: "SK" },
  { name: "Slovenian Euro", code: "EUR", iso_a2: "SI" },
  { name: "Solomon Islands Dollar", code: "SBD", iso_a2: "SB" },
  { name: "Somali Shilling", code: "SOS", iso_a2: "SO" },
  { name: "South African Rand", code: "ZAR", iso_a2: "ZA" },
  { name: "South Korean Won", code: "KRW", iso_a2: "KR" },
  { name: "South Sudanese Pound", code: "SSP", iso_a2: "SS" },
  { name: "Spanish Euro", code: "EUR", iso_a2: "ES" },
  { name: "Sri Lankan Rupee", code: "LKR", iso_a2: "LK" },
  { name: "Sudanese Pound", code: "SDG", iso_a2: "SD" },
  { name: "Surinamese Dollar", code: "SRD", iso_a2: "SR" },
  { name: "Swazi Lilangeni", code: "SZL", iso_a2: "SZ" },
  { name: "Swedish Krona", code: "SEK", iso_a2: "SE" },
  { name: "Swiss Franc", code: "CHF", iso_a2: "CH" },
  { name: "Syrian Pound", code: "SYP", iso_a2: "SY" },
  { name: "Tajikistani Somoni", code: "TJS", iso_a2: "TJ" },
  { name: "Tanzanian Shilling", code: "TZS", iso_a2: "TZ" },
  { name: "Thai Baht", code: "THB", iso_a2: "TH" },
  { name: "Trinidad & Tobago Dollar", code: "TTD", iso_a2: "TT" },
  { name: "Tunisian Dinar", code: "TND", iso_a2: "TN" },
  { name: "Turkish Lira", code: "TRY", iso_a2: "TR" },
  { name: "Turkmenistani Manat", code: "TMT", iso_a2: "TM" },
  { name: "Ugandan Shilling", code: "UGX", iso_a2: "UG" },
  { name: "Ukrainian Hryvnia", code: "UAH", iso_a2: "UA" },
  { name: "United Arab Emirates Dirham", code: "AED", iso_a2: "AE" },
  { name: "Uruguayan Peso", code: "UYU", iso_a2: "UY" },
  { name: "United States Dollar", code: "USD", iso_a2: "US" },
  { name: "Uzbekistan Som", code: "UZS", iso_a2: "UZ" },
  { name: "Vanuatu Vatu", code: "VUV", iso_a2: "VU" },
  { name: "Venezuelan BolÃvar", code: "VEF", iso_a2: "VE" },
  { name: "Vietnamese Dong", code: "VND", iso_a2: "VN" },
  { name: "Yemeni Rial", code: "YER", iso_a2: "YE" },
  { name: "Zambian Kwacha", code: "ZMK", iso_a2: "ZM" },
  { name: "Zimbabwean dollar", code: "ZWL", iso_a2: "ZW" },
  { name: "Palestine", code: "ILS", iso_a2: "PS" },
];
